version: '3.8'

services:
  ftp:
    image: fauria/vsftpd
    container_name: ftp-test
    restart: unless-stopped
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      FTP_USER: "testuser"
      FTP_PASS: "12345678"
      PASV_ADDRESS: host.docker.internal
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
      PASV_ADDR_RESOLVE: "YES"
      # optional:
      # LOG_STDOUT: "true"
    volumes:
      - ./ftpdata:/home/vsftpd

# pure-pw useradd test -u ftpuser -d /home/ftpusers/test -m